create table station (
  station_id varchar(64) primary key,
  station_name varchar(160) not null,
  timezone varchar(64) not null,
  status varchar(24) not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create table app_user (
  user_id varchar(80) primary key,
  display_name varchar(160) not null,
  enabled boolean not null,
  created_at timestamp with time zone not null
);

create table user_station_role (
  user_id varchar(80) not null references app_user(user_id),
  station_id varchar(64) not null references station(station_id),
  role_name varchar(32) not null,
  created_at timestamp with time zone not null,
  primary key (user_id, station_id, role_name)
);

create table main_switch_minute (
  minute_id bigint generated by default as identity primary key,
  station_id varchar(64) not null references station(station_id),
  event_time timestamp with time zone not null,
  arrival_time timestamp with time zone not null,
  active_power_kw double precision not null,
  phase_a_power_kw double precision not null,
  phase_b_power_kw double precision not null,
  phase_c_power_kw double precision not null,
  reactive_power_kvar double precision,
  voltage double precision,
  current_ampere double precision,
  power_factor double precision,
  coverage_ratio double precision not null,
  quality_flag varchar(24) not null,
  source_id varchar(128) not null,
  request_id varchar(80) not null,
  created_at timestamp with time zone not null,
  constraint uq_main_switch_station_time unique (station_id, event_time),
  constraint ck_main_switch_coverage check (coverage_ratio >= 0 and coverage_ratio <= 1)
);
create index ix_main_switch_station_time on main_switch_minute(station_id, event_time desc);

create table recognition_result (
  recognition_id varchar(64) primary key,
  station_id varchar(64) not null references station(station_id),
  event_time timestamp with time zone not null,
  result_time timestamp with time zone not null,
  input_window_start timestamp with time zone not null,
  input_window_end timestamp with time zone not null,
  interpolated_minutes integer not null,
  quality_status varchar(32) not null,
  model_version varchar(160) not null,
  model_summary text not null,
  deployment_role varchar(24) not null,
  request_id varchar(80) not null,
  created_at timestamp with time zone not null,
  constraint uq_recognition_result unique (station_id, event_time, model_version, deployment_role)
);

create table recognition_item (
  recognition_id varchar(64) not null references recognition_result(recognition_id) on delete cascade,
  kind varchar(32) not null,
  score double precision,
  detected boolean,
  feature_summary text not null,
  primary key (recognition_id, kind),
  constraint ck_recognition_kind check (kind in ('pv', 'energy_station', 'charger')),
  constraint ck_recognition_score check (score is null or (score >= 0 and score <= 1))
);

create table pv_separation_result (
  separation_id varchar(64) primary key,
  station_id varchar(64) not null references station(station_id),
  event_time timestamp with time zone not null,
  separation_time timestamp with time zone not null,
  input_window_start timestamp with time zone not null,
  input_window_end timestamp with time zone not null,
  interpolated_minutes integer not null,
  quality_status varchar(32) not null,
  total_power_kw double precision not null,
  initial_pv_kw double precision not null,
  pv_activity_probability double precision,
  corrected_pv_kw double precision,
  station_feedback_value double precision,
  correction_kw double precision,
  correction_ratio double precision,
  correction_confidence double precision,
  batch_id varchar(64),
  model_version varchar(160) not null,
  model_summary text not null,
  deployment_role varchar(24) not null,
  request_id varchar(80) not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  constraint uq_pv_separation unique (station_id, event_time, model_version, deployment_role),
  constraint ck_initial_pv_nonnegative check (initial_pv_kw >= 0)
);
create index ix_pv_separation_station_time on pv_separation_result(station_id, event_time desc);

create table pv_feedback_batch (
  batch_id varchar(64) primary key,
  station_id varchar(64) not null references station(station_id),
  arrival_time timestamp with time zone not null,
  coverage_start timestamp with time zone not null,
  coverage_end timestamp with time zone not null,
  interval_minutes integer not null,
  point_count integer not null,
  participant_nodes text not null,
  missing_nodes text not null,
  node_coverage_ratio double precision not null,
  capacity_coverage_ratio double precision not null,
  completeness_ratio double precision not null,
  quality_flag varchar(24) not null,
  request_id varchar(80) not null,
  created_at timestamp with time zone not null
);

create table pv_feedback_point (
  feedback_point_id varchar(64) primary key,
  batch_id varchar(64) not null references pv_feedback_batch(batch_id) on delete cascade,
  station_id varchar(64) not null references station(station_id),
  node_id varchar(64) not null,
  event_time timestamp with time zone not null,
  period_end timestamp with time zone not null,
  arrival_time timestamp with time zone not null,
  pv_value double precision not null,
  value_type varchar(24) not null,
  capacity_kw double precision not null,
  quality_flag varchar(24) not null,
  created_at timestamp with time zone not null,
  constraint uq_feedback_point unique (batch_id, node_id, event_time)
);

create table correction_record (
  correction_id varchar(64) primary key,
  station_id varchar(64) not null references station(station_id),
  separation_id varchar(64) not null references pv_separation_result(separation_id),
  batch_id varchar(64) not null references pv_feedback_batch(batch_id),
  period_start timestamp with time zone not null,
  period_end timestamp with time zone not null,
  before_kw double precision not null,
  reference_kw double precision not null,
  after_kw double precision not null,
  correction_kw double precision not null,
  confidence double precision not null,
  reason text not null,
  request_id varchar(80) not null,
  updated_at timestamp with time zone not null,
  constraint uq_correction_separation_batch unique (separation_id, batch_id)
);

create table model_registry (
  model_version varchar(160) primary key,
  model_id varchar(160) not null,
  task varchar(64) not null,
  artifact_sha256 varchar(64) not null,
  manifest_json text not null,
  lifecycle_status varchar(32) not null,
  registered_by varchar(80) not null,
  registered_at timestamp with time zone not null,
  approved_by varchar(80),
  approved_at timestamp with time zone,
  constraint uq_model_artifact unique (task, artifact_sha256)
);

create table model_deployment (
  deployment_id varchar(64) primary key,
  station_id varchar(64) references station(station_id),
  task varchar(64) not null,
  model_version varchar(160) not null references model_registry(model_version),
  deployment_role varchar(24) not null,
  status varchar(32) not null,
  previous_model_version varchar(160),
  health_status varchar(32) not null,
  deployed_by varchar(80) not null,
  deployed_at timestamp with time zone not null,
  retired_at timestamp with time zone
);
create index ix_model_deployment_active on model_deployment(task, deployment_role, status);

create table shadow_inference_comparison (
  comparison_id varchar(64) primary key,
  station_id varchar(64) not null references station(station_id),
  event_time timestamp with time zone not null,
  task varchar(64) not null,
  active_model_version varchar(160) not null,
  candidate_model_version varchar(160) not null,
  active_result_json text not null,
  candidate_result_json text not null,
  difference_json text not null,
  request_id varchar(80) not null,
  created_at timestamp with time zone not null
);

create table training_run (
  run_id varchar(64) primary key,
  station_id varchar(64) references station(station_id),
  status varchar(24) not null,
  model_version varchar(160) not null,
  dataset_window_days integer not null,
  sample_count integer not null,
  started_at timestamp with time zone not null,
  completed_at timestamp with time zone,
  validation_score double precision,
  source_record text not null,
  created_at timestamp with time zone not null
);

create table training_epoch (
  run_id varchar(64) not null references training_run(run_id) on delete cascade,
  epoch integer not null,
  training_loss double precision not null,
  validation_score double precision not null,
  recorded_at timestamp with time zone not null,
  primary key (run_id, epoch)
);

create table collection_process_event (
  event_id varchar(80) primary key,
  station_id varchar(64) not null references station(station_id),
  request_id varchar(80) not null,
  event_type varchar(64) not null,
  status varchar(24) not null,
  detail_json text not null,
  occurred_at timestamp with time zone not null
);

create table node_status (
  station_id varchar(64) not null references station(station_id),
  node_id varchar(64) not null,
  node_name varchar(160) not null,
  capacity_kw double precision not null,
  communication_status varchar(24) not null,
  latest_event_time timestamp with time zone,
  latest_arrival_time timestamp with time zone,
  quality_flag varchar(24) not null,
  updated_at timestamp with time zone not null,
  primary key (station_id, node_id)
);

create table data_quality_summary (
  station_id varchar(64) primary key references station(station_id),
  completeness_ratio double precision not null,
  duplicate_count bigint not null,
  missing_count bigint not null,
  out_of_order_count bigint not null,
  warning_count bigint not null,
  last_checked_at timestamp with time zone not null
);

create table audit_log (
  audit_id varchar(80) primary key,
  request_id varchar(80) not null,
  actor_id varchar(80) not null,
  action varchar(80) not null,
  resource_type varchar(80) not null,
  resource_id varchar(160),
  station_id varchar(64),
  outcome varchar(24) not null,
  client_address varchar(128),
  detail_json text not null,
  occurred_at timestamp with time zone not null
);
create index ix_audit_actor_time on audit_log(actor_id, occurred_at desc);

create table outbox_event (
  event_id varchar(80) primary key,
  request_id varchar(80) not null,
  station_id varchar(64) not null,
  event_type varchar(80) not null,
  payload_json text not null,
  occurred_at timestamp with time zone not null,
  published_at timestamp with time zone,
  publish_attempts integer not null,
  last_error varchar(500)
);
create index ix_outbox_unpublished on outbox_event(published_at, occurred_at);
